### ISSUE TITLE
Write event data to AWS S3

### ISSUE THREAD

**Issue by PSalant726** [ethyca/fideslog#10]
Because of startup latency associated with Snowflake, per-event queries to write event data directly to the database may run inefficiently. Instead, event data should be written to a new S3 bucket.

A new, secure S3 bucket must be created. Access to this S3 bucket should be minimal, and the fideslog service must have write access.

Event data should be batched prior to uploading, using a combination of time- and size-based batching (ex. _publish to S3 every five minutes, or each time the buffer exceeds 1MB in size_).

Some additional things to consider are:
- What is the optimal file type to publish to S3?
- How should the event data be structured for upload?
- Should uploads stream to existing files in the S3 bucket, or create a new one each time?

**This is in addition to writing events directly to Snowflake; no code affecting Snowflake DB interactions should be removed. Future work will remove the direct Snowflake interaction mechanism.**

**Comment by SteveDMurphy** [comment]
> @PSalant726, have you considered using AWS Kinesis Firehose for batching/flushing to S3? Instead of writing directly to S3, I'd suggest we write to Kinesis Data Firehose and allow it to write to S3. I believe that this would allow for a more scalable solution in the long term.

I think this is definitely something to consider as a next step!  For immediate action I think the combined efforts of reducing unnecessary logging (i.e. `health/`) and writing to S3 should give us a simple solution to then look at how we can take advantage of Kinesis
